### PR TITLE
To make it compatible with gitolite's personal branches

### PR DESCRIPTION
**Pull request by juasiepo**
http://gitolite.com/gitolite/user.html#pers

Gitolite uses personal branches personal/user/label and rk10 transforms the "/" to "_"
It is necessary to detect personal branches and make the substitution

### CODE REVIEW

**Comment by sciurus** [comment]
Thanks for addressing this. I'm not in a good position to test it. It looks fine, but have you verified it behaves properly with standard and personal branches?

Is there something special about personal branches, or is this transformation of `/` to `_` need for any branches with a slash in the name?

Why do we need to transform the name before giving it to r10k? Based on the [invalid_branches](https://github.com/adrienthebo/r10k/blob/master/doc/dynamic-environments/git-environments.mkd) documentation it sound like r10k should convert the characters itself by default.

**Comment by juasiepo** [comment]
> but have you verified it behaves properly with standard and personal branches?

Yes, I have tested it and works as expected.

> or is this transformation of / to _ need for any branches with a slash in the name?

Gitolite enforces the creation on personal branches using the personal/user/label. Thats the only way to create them. The problem working with gitolite is that the branch is named personal/user/label and the r10k environment to be deployed is "personal_user_label".

> Why do we need to transform the name before giving it to r10k?

Let's use **r10k deploy display** to illustrate it:
[R10K::Source::Git - WARN] Environment "personal/user/label" contained non-word characters, correcting name to personal_user_label
- personal_user_label

In your version r10k is called like this:
/usr/local/bin/r10k deploy environment **personal/user/label** -p
Because there is not any environment called personal/user/label, nothing is deployed. The way to call it is 
/usr/local/bin/r10k deploy environment **personal_user_label** -p

That's the reason I am detecting the personal\* string.

I hope I have made myself clear!

Thanks for your time

**Comment by sciurus** [comment]
> Gitolite enforces the creation on personal branches using the personal/user/label.

I get that personal branches must have slashes in the name. However, other kinds of branches can have slashes in the name too. We should handle the general rather than the specific case.

I still think this PR isn't necessary though, because `/usr/local/bin/r10k deploy environment personal/user/label -p` _should_ work.

r10k should automatically convert _personal/user/label_ to _personal_user_label_ for us. See [this code](https://github.com/puppetlabs/r10k/blob/90cffb9f5b2adf385f3c3e4962f3b4de9ae260cd/lib/r10k/action/deploy/environment.rb#L16) Are you trying this with the latest r10k, version 1.4.1? I think maybe you have an earlier version with a bug puppetlabs/r10k#260 that prevents it from working.

**Comment by juasiepo** [comment]
You are right. with the 1.4.1 version it is not necessary the modification. You can discard this.

Best regards

**Comment by sciurus** [comment]
Okay; I'm glad everything is straightened out!

**Pull request closed without merging**
